method = "casmikka11 式アストラル鍛錬法"

[[steps]]
step = 1
description = "絵のないファンタジー系の物語を読む"
purpose = "内的想像力の活性化"
notes = "単純な王子様とお姫様の話がイメージしやすい"

[[steps]]
step = 2
description = "登場人物の姿を思いうかべる"
purpose = "イメージ投影の訓練"
notes = "似たような顔でもOK。目と鼻があるだけでも良い"

[[steps]]
step = 3
description = "映画をみるようにして全体を再生"
purpose = "内的シミュレーション能力の強化"

[[steps]]
step = 4
description = "自分がその登場人物になったかのように感じる"
purpose = "五感・感情の疑似体験"
notes = "憑依型共感の訓練"

[caution]
text = "現実的な体験が伴わないとイメージしづらい。食べたことのない物だと水をくぐらせたティッシュの味がする"
